service: hello-database-client

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  #profile: serverless-admin

plugins:
  - serverless-finch

custom:
  client:
    bucketName: hello-database-client-bucket
    distributionFolder: client/dist 
    indexDocument: index.html
    errorDocument: index.html